# Generated by Django 5.2.17 on 2026-10-04 22:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(db_index=True, max_length=30)),
                ('full_name', models.CharField(max_length=120)),
                ('phone_primary', models.CharField(db_index=True, max_length=20)),
                ('phone_secondary', models.CharField(blank=True, max_length=20, null=True)),
                ('national_id', models.CharField(db_index=True, help_text='Format: XXXXX-XXXXXXX-X', max_length=15, validators=[django.core.validators.RegexValidator(code='invalid_national_id', message='National ID must be in the format XXXXX-XXXXXXX-X', regex='^\\d{5}-\\d{7}-\\d{1}$')])),
                ('home_address', models.TextField()),
                ('workplace_address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('owner_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('relationship', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('national_id', models.CharField(help_text='Format: XXXXX-XXXXXXX-X', max_length=15, validators=[django.core.validators.RegexValidator(code='invalid_national_id', message='National ID must be in the format XXXXX-XXXXXXX-X', regex='^\\d{5}-\\d{7}-\\d{1}$')])),
                ('home_address', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantors', to='catalog_customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=80)),
                ('model_name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('REFRIGERATOR', 'Refrigerator'), ('WASHING_MACHINE', 'Washing Machine'), ('OVEN', 'Microwave / Oven'), ('MOBILE', 'Mobile Phone'), ('AIR_CONDITIONER', 'Air Conditioner'), ('OTHER', 'Other Appliance')], max_length=50)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cash_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog_customers.shop')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='catalog_customers.shop'),
        ),
        migrations.CreateModel(
            name='SerializedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('IN_STOCK', 'In Stock'), ('ALLOCATED_TO_INSTALLMENT', 'Sold on Installment'), ('SOLD_CASH', 'Sold Cash'), ('DEFECTIVE', 'Defective / Returned')], default='IN_STOCK', max_length=30)),
                ('received_date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serialized_units', to='catalog_customers.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product', 'serial_number'), name='unique_serial_per_product')],
            },
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('shop', 'customer_id'), name='unique_customer_per_shop'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('shop', 'national_id'), name='unique_national_id_per_shop'),
        ),
    ]
