# Generated by Django 5.2.17 on 2026-10-05 21:04

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog_customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('tenure_months', models.PositiveSmallIntegerField(choices=[(3, '3 Months'), (6, '6 Months'), (12, '12 Months')])),
                ('product_cash_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('down_payment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('financed_principal', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('markup_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('markup_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('total_financed_payable', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('monthly_installment', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('remaining_balance', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Fully Paid'), ('DEFAULTED', 'Defaulted / Recovery')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='catalog_customers.customer')),
                ('serialized_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='catalog_customers.serializeditem')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='catalog_customers.shop')),
            ],
        ),
        migrations.CreateModel(
            name='InstallmentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveSmallIntegerField()),
                ('due_date', models.DateField(db_index=True)),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('remaining_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Fully Paid'), ('OVERDUE', 'Overdue')], db_index=True, default='PENDING', max_length=20)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='contracts.installmentcontract')),
            ],
            options={
                'ordering': ['installment_number'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField(default=datetime.date.today)),
                ('manual_receipt_no', models.CharField(db_index=True, max_length=60)),
                ('collector_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='contracts.installmentcontract')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='contracts.installmentschedule')),
            ],
        ),
        migrations.AddConstraint(
            model_name='installmentschedule',
            constraint=models.UniqueConstraint(fields=('contract', 'installment_number'), name='unique_schedule_month'),
        ),
    ]
