# Generated by Django 5.2.17 on 2026-10-06 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installmentschedule',
            options={'ordering': ['contract', 'installment_number']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date', '-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='installmentschedule',
            name='unique_schedule_month',
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('contract', 'manual_receipt_no'), name='unique_contract_receipt_slip'),
        ),
    ]
